from typing import Optional
from models import (
    Patient, Medication, AdverseEvent, ProgressionAssessment,
    TreatmentCycle, Visit, VitalSigns,
)

PATIENT_1 = Patient(
    id="PT-001", name="Margaret Chen", age=62, sex="F", dob="1962-03-14",
    mrn="MRN-7821034", trial_id="ONCO-LUNG-2024-A", site="Memorial Cancer Center",
    enrollment_date="2024-02-10", status="Active", cancer_type="NSCLC",
    cancer_subtype="Adenocarcinoma", stage="IIIB",
    biomarkers=["PD-L1 TPS 72%", "KRAS G12C", "TMB-High"], ecog=1,
    arm="Arm A: Pembro + Carbo/Pem", current_cycle=6, total_cycles=6,
    best_response="PR", physician="Dr. Sarah Okonkwo", coordinator="James Reeves",
    notes="Tolerating treatment well. Dose reduction for fatigue in cycle 4.",
    medications=[
        Medication(id="MED-001", name="Pembrolizumab", category="Immunotherapy",
                   dose=200, unit="mg", route="IV", frequency="Q3W",
                   start_date="2024-02-15", status="Active", cycle_number=6),
        Medication(id="MED-002", name="Carboplatin", category="Chemotherapy",
                   dose=5, unit="AUC", route="IV", frequency="Q3W",
                   start_date="2024-02-15", end_date="2024-07-01",
                   status="Completed", cycle_number=4,
                   discontinued_reason="Completed 4 cycles per protocol"),
        Medication(id="MED-003", name="Pemetrexed", category="Chemotherapy",
                   dose=500, unit="mg/m2", route="IV", frequency="Q3W",
                   start_date="2024-02-15", status="Active", cycle_number=6),
        Medication(id="MED-004", name="Ondansetron", category="Supportive",
                   dose=8, unit="mg", route="Oral", frequency="PRN nausea",
                   start_date="2024-02-15", status="Active"),
    ],
    adverse_events=[
        AdverseEvent(id="AE-001", term="Fatigue", category="General disorders",
                     grade=2, onset="2024-03-20", outcome="Resolving",
                     action="Dose Reduction", related_to_treatment=True, date="2024-03-22",
                     notes="Dose reduced 20% in cycle 4; improving"),
        AdverseEvent(id="AE-002", term="Nausea", category="Gastrointestinal",
                     grade=1, onset="2024-02-20", resolution="2024-04-01",
                     outcome="Resolved", action="None", related_to_treatment=True, date="2024-02-22"),
        AdverseEvent(id="AE-003", term="Pneumonitis", category="Respiratory",
                     grade=3, onset="2024-05-10", outcome="Resolving",
                     action="Drug Holiday", related_to_treatment=True, date="2024-05-12",
                     notes="Immune-mediated pneumonitis. Pembrolizumab held. Starting prednisone 1mg/kg."),
    ],
    progression_assessments=[
        ProgressionAssessment(id="PA-001", date="2024-02-10", method="CT",
                              response="NE", tumor_burden_mm=45.2, percent_change=0,
                              target_lesions=2, non_target_lesions="Present",
                              new_lesions=False, notes="Baseline scan"),
        ProgressionAssessment(id="PA-002", date="2024-05-01", method="CT",
                              response="PR", tumor_burden_mm=28.7, percent_change=-36.5,
                              target_lesions=2, non_target_lesions="Stable",
                              new_lesions=False, notes="Confirmed partial response"),
    ],
    cycles=[
        TreatmentCycle(id="CYC-001", cycle_number=1, start_date="2024-02-15", end_date="2024-03-07", status="Completed"),
        TreatmentCycle(id="CYC-002", cycle_number=2, start_date="2024-03-07", end_date="2024-03-28", status="Completed"),
        TreatmentCycle(id="CYC-003", cycle_number=3, start_date="2024-03-28", end_date="2024-04-18", status="Completed"),
        TreatmentCycle(id="CYC-004", cycle_number=4, start_date="2024-04-18", end_date="2024-05-09", status="Completed",
                       dose_modification="Pemetrexed 20% reduction for fatigue"),
        TreatmentCycle(id="CYC-005", cycle_number=5, start_date="2024-05-30", end_date="2024-06-20", status="Completed",
                       delay_reason="Pneumonitis workup — 3-week hold"),
        TreatmentCycle(id="CYC-006", cycle_number=6, start_date="2024-06-20", status="Active"),
    ],
    visits=[
        Visit(id="V-001", date="2024-02-10", type="Screening", provider="Dr. Okonkwo",
              notes="Baseline assessment. ECOG 1. Staging complete.", ecog=1,
              vitals=VitalSigns(bp="122/78", hr=74, temp=36.8, weight=68.0, o2sat=97)),
        Visit(id="V-002", date="2024-05-01", type="Cycle Mid", provider="Dr. Okonkwo",
              notes="Response assessment visit. PR confirmed.", ecog=1,
              vitals=VitalSigns(bp="118/76", hr=72, temp=36.9, weight=65.5, o2sat=96)),
    ],
)

PATIENT_2 = Patient(
    id="PT-002", name="Robert Alvarez", age=54, sex="M", dob="1970-07-22",
    mrn="MRN-4419823", trial_id="ONCO-CRC-2023-B", site="University Medical Center",
    enrollment_date="2023-09-05", status="Active", cancer_type="Colorectal",
    cancer_subtype="MSI-H Adenocarcinoma", stage="IV",
    biomarkers=["MSI-H", "MMR Deficient", "BRAF V600E", "TMB 42 mut/Mb"], ecog=0,
    arm="Arm B: Nivolumab + Ipilimumab", current_cycle=8, total_cycles=4,
    best_response="CR", physician="Dr. Marcus Webb", coordinator="Lisa Park",
    notes="Exceptional responder. Complete response at cycle 4 assessment. On maintenance.",
    medications=[
        Medication(id="MED-010", name="Nivolumab", category="Immunotherapy",
                   dose=240, unit="mg", route="IV", frequency="Q2W",
                   start_date="2023-09-10", status="Active", cycle_number=8),
        Medication(id="MED-011", name="Ipilimumab", category="Immunotherapy",
                   dose=1, unit="mg/kg", route="IV", frequency="Q6W",
                   start_date="2023-09-10", end_date="2024-01-15",
                   status="Completed", cycle_number=4,
                   discontinued_reason="4 doses per protocol completed"),
    ],
    adverse_events=[
        AdverseEvent(id="AE-010", term="Diarrhea", category="Gastrointestinal",
                     grade=2, onset="2023-10-20", resolution="2023-11-15",
                     outcome="Resolved", action="None", related_to_treatment=True, date="2023-10-22"),
        AdverseEvent(id="AE-011", term="Hypothyroidism", category="Endocrine",
                     grade=1, onset="2023-12-01", outcome="Ongoing",
                     action="None", related_to_treatment=True, date="2023-12-05",
                     notes="On levothyroxine 50mcg daily"),
    ],
    progression_assessments=[
        ProgressionAssessment(id="PA-010", date="2023-09-05", method="CT",
                              response="NE", tumor_burden_mm=52.1, percent_change=0,
                              target_lesions=3, non_target_lesions="Present",
                              new_lesions=False, notes="Baseline"),
        ProgressionAssessment(id="PA-011", date="2023-12-01", method="CT",
                              response="PR", tumor_burden_mm=18.4, percent_change=-64.7,
                              target_lesions=3, non_target_lesions="Stable",
                              new_lesions=False, notes="Deep partial response"),
        ProgressionAssessment(id="PA-012", date="2024-03-05", method="PET-CT",
                              response="CR", tumor_burden_mm=0.0, percent_change=-100.0,
                              target_lesions=0, non_target_lesions="Absent",
                              new_lesions=False, notes="Complete metabolic response."),
    ],
    cycles=[
        TreatmentCycle(id="CYC-010", cycle_number=1, start_date="2023-09-10", end_date="2023-09-24", status="Completed"),
        TreatmentCycle(id="CYC-011", cycle_number=2, start_date="2023-09-24", end_date="2023-10-08", status="Completed"),
        TreatmentCycle(id="CYC-012", cycle_number=3, start_date="2023-10-08", end_date="2023-10-22", status="Completed"),
        TreatmentCycle(id="CYC-013", cycle_number=4, start_date="2023-10-22", end_date="2023-11-05", status="Completed"),
        TreatmentCycle(id="CYC-014", cycle_number=5, start_date="2023-11-05", end_date="2023-11-19", status="Completed"),
        TreatmentCycle(id="CYC-015", cycle_number=6, start_date="2023-11-19", end_date="2023-12-03", status="Completed"),
        TreatmentCycle(id="CYC-016", cycle_number=7, start_date="2023-12-03", end_date="2023-12-17", status="Completed"),
        TreatmentCycle(id="CYC-017", cycle_number=8, start_date="2023-12-17", status="Active"),
    ],
    visits=[
        Visit(id="V-010", date="2023-09-05", type="Screening", provider="Dr. Webb",
              notes="Baseline. MSI-H confirmed on reflex testing.", ecog=0,
              vitals=VitalSigns(bp="124/80", hr=68, temp=36.7, weight=82.0, o2sat=98)),
        Visit(id="V-011", date="2024-03-05", type="Follow-up", provider="Dr. Webb",
              notes="CR confirmed on PET-CT. Exceptional response.", ecog=0,
              vitals=VitalSigns(bp="120/78", hr=65, temp=36.6, weight=83.5, o2sat=99)),
    ],
)

PATIENT_3 = Patient(
    id="PT-003", name="Aisha Oduya", age=41, sex="F", dob="1983-11-30",
    mrn="MRN-9934712", trial_id="ONCO-BREAST-2024-C", site="Women's Cancer Institute",
    enrollment_date="2024-01-20", status="Active", cancer_type="Breast",
    cancer_subtype="HER2+ ER- PR-", stage="IV",
    biomarkers=["HER2 3+ IHC", "HER2 amplified FISH", "PIK3CA H1047R"], ecog=1,
    arm="Arm C: T-DXd monotherapy", current_cycle=4, total_cycles=6,
    best_response="SD", physician="Dr. Priya Mehta", coordinator="Tom Garcia",
    notes="ILD monitoring ongoing. Grade 3 ILD episode resolved. Currently on reduced dose.",
    medications=[
        Medication(id="MED-020", name="Trastuzumab deruxtecan", category="Targeted",
                   dose=5.4, unit="mg/kg", route="IV", frequency="Q3W",
                   start_date="2024-01-25", status="Active", cycle_number=4),
        Medication(id="MED-021", name="Dexamethasone", category="Supportive",
                   dose=4, unit="mg", route="Oral", frequency="Q8H premedication",
                   start_date="2024-01-25", status="Active"),
        Medication(id="MED-022", name="Prednisolone", category="Supportive",
                   dose=1, unit="mg/kg", route="Oral", frequency="Daily",
                   start_date="2024-04-05", end_date="2024-05-20",
                   status="Completed", discontinued_reason="ILD treatment course completed"),
    ],
    adverse_events=[
        AdverseEvent(id="AE-020", term="Interstitial Lung Disease", category="Respiratory",
                     grade=3, onset="2024-04-01", resolution="2024-05-15",
                     outcome="Resolved", action="Drug Holiday", related_to_treatment=True,
                     date="2024-04-03",
                     notes="Grade 3 ILD. T-DXd held 6 weeks. Systemic steroids. Restarted at reduced dose."),
        AdverseEvent(id="AE-021", term="Nausea", category="Gastrointestinal",
                     grade=2, onset="2024-02-01", outcome="Ongoing",
                     action="None", related_to_treatment=True, date="2024-02-03"),
        AdverseEvent(id="AE-022", term="Alopecia", category="Skin",
                     grade=2, onset="2024-02-15", outcome="Ongoing",
                     action="None", related_to_treatment=True, date="2024-02-18"),
        AdverseEvent(id="AE-023", term="Thrombocytopenia", category="Blood",
                     grade=3, onset="2024-05-20", outcome="Resolving",
                     action="Dose Reduction", related_to_treatment=True, date="2024-05-22",
                     notes="Platelets 52k. Dose reduced 20%. Weekly CBC monitoring."),
    ],
    progression_assessments=[
        ProgressionAssessment(id="PA-020", date="2024-01-20", method="CT",
                              response="NE", tumor_burden_mm=38.4, percent_change=0,
                              target_lesions=2, non_target_lesions="Present",
                              new_lesions=False, notes="Baseline — multiple bone mets, liver lesion"),
        ProgressionAssessment(id="PA-021", date="2024-04-20", method="CT",
                              response="SD", tumor_burden_mm=35.1, percent_change=-8.6,
                              target_lesions=2, non_target_lesions="Stable",
                              new_lesions=False, notes="Stable disease. Minor decrease in liver lesion."),
    ],
    cycles=[
        TreatmentCycle(id="CYC-020", cycle_number=1, start_date="2024-01-25", end_date="2024-02-15", status="Completed"),
        TreatmentCycle(id="CYC-021", cycle_number=2, start_date="2024-02-15", end_date="2024-03-07", status="Completed"),
        TreatmentCycle(id="CYC-022", cycle_number=3, start_date="2024-03-07", end_date="2024-03-28", status="Completed"),
        TreatmentCycle(id="CYC-023", cycle_number=4, start_date="2024-05-20", status="Active",
                       delay_reason="6-week hold for Grade 3 ILD",
                       dose_modification="T-DXd reduced to 4.4 mg/kg"),
    ],
    visits=[
        Visit(id="V-020", date="2024-01-20", type="Screening", provider="Dr. Mehta",
              notes="Baseline. Brain MRI negative.", ecog=1,
              vitals=VitalSigns(bp="126/82", hr=82, temp=36.8, weight=62.0, o2sat=97)),
        Visit(id="V-021", date="2024-04-03", type="Unscheduled", provider="Dr. Mehta",
              notes="Urgent visit for dyspnea. CT confirmed Grade 3 ILD.", ecog=2,
              vitals=VitalSigns(bp="130/88", hr=96, temp=37.2, weight=60.5, o2sat=92)),
    ],
)

PATIENT_4 = Patient(
    id="PT-004", name="William Foster", age=71, sex="M", dob="1953-05-18",
    mrn="MRN-2267891", trial_id="ONCO-PROST-2023-D", site="Veterans Cancer Center",
    enrollment_date="2023-11-14", status="Active", cancer_type="Prostate",
    cancer_subtype="CRPC", stage="IV",
    biomarkers=["BRCA2 mutation", "HRR positive", "PSA 48.2 ng/mL"], ecog=2,
    arm="Arm D: Olaparib + Enzalutamide", current_cycle=3, total_cycles=6,
    best_response="PD", physician="Dr. Kenneth Blair", coordinator="Rachel Moore",
    notes="PSA rising despite treatment. Bone mets progressing. Considering early discontinuation.",
    medications=[
        Medication(id="MED-030", name="Olaparib", category="Targeted",
                   dose=300, unit="mg", route="Oral", frequency="BID",
                   start_date="2023-11-20", status="Active", cycle_number=3),
        Medication(id="MED-031", name="Enzalutamide", category="Hormonal",
                   dose=160, unit="mg", route="Oral", frequency="Daily",
                   start_date="2023-11-20", status="Active", cycle_number=3),
        Medication(id="MED-032", name="Zoledronic Acid", category="Supportive",
                   dose=4, unit="mg", route="IV", frequency="Q4W",
                   start_date="2023-11-20", status="Active"),
    ],
    adverse_events=[
        AdverseEvent(id="AE-030", term="Anemia", category="Blood",
                     grade=3, onset="2024-01-10", outcome="Ongoing",
                     action="Dose Reduction", related_to_treatment=True, date="2024-01-12",
                     notes="Hgb 7.8. Olaparib reduced to 200mg BID. Monitoring weekly CBC."),
        AdverseEvent(id="AE-031", term="Fatigue", category="General disorders",
                     grade=3, onset="2024-02-01", outcome="Ongoing",
                     action="None", related_to_treatment=True, date="2024-02-03",
                     notes="ECOG declining. Consider dose hold."),
        AdverseEvent(id="AE-032", term="Nausea", category="Gastrointestinal",
                     grade=1, onset="2023-12-01", resolution="2024-01-01",
                     outcome="Resolved", action="None", related_to_treatment=True, date="2023-12-03"),
    ],
    progression_assessments=[
        ProgressionAssessment(id="PA-030", date="2023-11-14", method="CT",
                              response="NE", tumor_burden_mm=0, percent_change=0,
                              target_lesions=0, non_target_lesions="Bone mets",
                              new_lesions=False, notes="Baseline — bone-only disease"),
        ProgressionAssessment(id="PA-031", date="2024-02-14", method="CT",
                              response="PD", tumor_burden_mm=0, percent_change=0,
                              target_lesions=0, non_target_lesions="Progressing bone mets",
                              new_lesions=True, notes="New bone lesions: T8, right iliac. PSA 72.1 ng/mL."),
    ],
    cycles=[
        TreatmentCycle(id="CYC-030", cycle_number=1, start_date="2023-11-20", end_date="2023-12-20", status="Completed"),
        TreatmentCycle(id="CYC-031", cycle_number=2, start_date="2023-12-20", end_date="2024-01-20", status="Completed",
                       dose_modification="Olaparib reduced 200mg BID for anemia"),
        TreatmentCycle(id="CYC-032", cycle_number=3, start_date="2024-01-20", status="Active"),
    ],
    visits=[
        Visit(id="V-030", date="2023-11-14", type="Screening", provider="Dr. Blair",
              notes="Baseline. ECOG 2. Multiple bone mets confirmed.", ecog=2,
              vitals=VitalSigns(bp="142/88", hr=78, temp=36.7, weight=91.0, o2sat=96)),
        Visit(id="V-031", date="2024-02-14", type="Follow-up", provider="Dr. Blair",
              notes="Disease progression confirmed. Tumor board review scheduled.", ecog=2,
              vitals=VitalSigns(bp="148/90", hr=82, temp=36.8, weight=88.0, o2sat=95)),
    ],
)

PATIENT_5 = Patient(
    id="PT-005", name="Elena Vasquez", age=48, sex="F", dob="1976-09-03",
    mrn="MRN-5583210", trial_id="ONCO-MELA-2022-E", site="Skin Cancer Research Institute",
    enrollment_date="2022-06-15", status="Completed", cancer_type="Melanoma",
    cancer_subtype="Cutaneous BRAF V600E", stage="IV",
    biomarkers=["BRAF V600E", "TMB-High", "PD-L1 TPS 85%"], ecog=0,
    arm="Arm E: Dabrafenib + Trametinib", current_cycle=12, total_cycles=12,
    best_response="CR", physician="Dr. Amy Fischer", coordinator="Carlos Mendez",
    notes="Completed 12 cycles. CR maintained. Off treatment, surveillance phase.",
    medications=[
        Medication(id="MED-040", name="Dabrafenib", category="Targeted",
                   dose=150, unit="mg", route="Oral", frequency="BID",
                   start_date="2022-06-20", end_date="2023-06-20",
                   status="Completed", cycle_number=12,
                   discontinued_reason="Protocol completion — 12 cycles"),
        Medication(id="MED-041", name="Trametinib", category="Targeted",
                   dose=2, unit="mg", route="Oral", frequency="Daily",
                   start_date="2022-06-20", end_date="2023-06-20",
                   status="Completed", cycle_number=12,
                   discontinued_reason="Protocol completion — 12 cycles"),
    ],
    adverse_events=[
        AdverseEvent(id="AE-040", term="Pyrexia", category="General disorders",
                     grade=2, onset="2022-07-15", resolution="2022-07-25",
                     outcome="Resolved", action="Drug Holiday", related_to_treatment=True,
                     date="2022-07-16", notes="BRAF-inhibitor related fever. 7-day hold. Resolved."),
        AdverseEvent(id="AE-041", term="Arthralgia", category="Musculoskeletal",
                     grade=1, onset="2022-08-01", resolution="2023-01-01",
                     outcome="Resolved", action="None", related_to_treatment=True, date="2022-08-03"),
    ],
    progression_assessments=[
        ProgressionAssessment(id="PA-040", date="2022-06-15", method="PET-CT",
                              response="NE", tumor_burden_mm=34.8, percent_change=0,
                              target_lesions=3, non_target_lesions="Present",
                              new_lesions=False, notes="Baseline — hepatic and nodal mets"),
        ProgressionAssessment(id="PA-041", date="2022-09-15", method="CT",
                              response="PR", tumor_burden_mm=12.4, percent_change=-64.4,
                              target_lesions=3, non_target_lesions="Stable",
                              new_lesions=False, notes="Rapid deep response"),
        ProgressionAssessment(id="PA-042", date="2022-12-15", method="CT",
                              response="CR", tumor_burden_mm=0.0, percent_change=-100.0,
                              target_lesions=0, non_target_lesions="Absent",
                              new_lesions=False, notes="Complete response confirmed"),
        ProgressionAssessment(id="PA-043", date="2023-06-20", method="PET-CT",
                              response="CR", tumor_burden_mm=0.0, percent_change=-100.0,
                              target_lesions=0, non_target_lesions="Absent",
                              new_lesions=False, notes="CR maintained at treatment completion"),
    ],
    cycles=[
        TreatmentCycle(id="CYC-041", cycle_number=1,  start_date="2022-06-20", end_date="2022-07-20", status="Completed"),
        TreatmentCycle(id="CYC-042", cycle_number=2,  start_date="2022-07-20", end_date="2022-08-20", status="Completed"),
        TreatmentCycle(id="CYC-043", cycle_number=3,  start_date="2022-08-20", end_date="2022-09-20", status="Completed"),
        TreatmentCycle(id="CYC-044", cycle_number=4,  start_date="2022-09-20", end_date="2022-10-20", status="Completed"),
        TreatmentCycle(id="CYC-045", cycle_number=5,  start_date="2022-10-20", end_date="2022-11-20", status="Completed"),
        TreatmentCycle(id="CYC-046", cycle_number=6,  start_date="2022-11-20", end_date="2022-12-20", status="Completed"),
        TreatmentCycle(id="CYC-047", cycle_number=7,  start_date="2022-12-20", end_date="2023-01-20", status="Completed"),
        TreatmentCycle(id="CYC-048", cycle_number=8,  start_date="2023-01-20", end_date="2023-02-20", status="Completed"),
        TreatmentCycle(id="CYC-049", cycle_number=9,  start_date="2023-02-20", end_date="2023-03-20", status="Completed"),
        TreatmentCycle(id="CYC-050b", cycle_number=10, start_date="2023-03-20", end_date="2023-04-20", status="Completed"),
        TreatmentCycle(id="CYC-051b", cycle_number=11, start_date="2023-04-20", end_date="2023-05-20", status="Completed"),
        TreatmentCycle(id="CYC-052b", cycle_number=12, start_date="2023-05-20", end_date="2023-06-20", status="Completed"),
    ],
    visits=[
        Visit(id="V-040", date="2022-06-15", type="Screening", provider="Dr. Fischer",
              notes="Baseline. Good performance status.", ecog=0,
              vitals=VitalSigns(bp="112/72", hr=64, temp=36.6, weight=72.0, o2sat=99)),
        Visit(id="V-041", date="2023-06-20", type="End of Treatment", provider="Dr. Fischer",
              notes="Protocol completion. CR maintained. Entering surveillance.", ecog=0,
              vitals=VitalSigns(bp="114/70", hr=66, temp=36.5, weight=73.5, o2sat=99)),
    ],
)

PATIENT_6 = Patient(
    id="PT-006", name="James Okafor", age=67, sex="M", dob="1957-02-28",
    mrn="MRN-8812947", trial_id="ONCO-AML-2024-F", site="Hematology Excellence Center",
    enrollment_date="2024-03-01", status="Active", cancer_type="AML",
    cancer_subtype="FLT3-ITD+", stage="Newly Diagnosed",
    biomarkers=["FLT3-ITD+", "NPM1 mutated", "IDH2 mutated", "Normal karyotype"], ecog=1,
    arm="Arm F: 7+3 + Midostaurin", current_cycle=1, total_cycles=2,
    best_response="NE", physician="Dr. Ingrid Larsson", coordinator="David Kim",
    notes="Induction cycle 1 ongoing. Bone marrow biopsy day 14 showing blast clearance.",
    medications=[
        Medication(id="MED-050", name="Cytarabine", category="Chemotherapy",
                   dose=100, unit="mg/m2", route="IV", frequency="Q12H days 1-7",
                   start_date="2024-03-05", status="Active", cycle_number=1),
        Medication(id="MED-051", name="Daunorubicin", category="Chemotherapy",
                   dose=60, unit="mg/m2", route="IV", frequency="Daily days 1-3",
                   start_date="2024-03-05", status="Active", cycle_number=1),
        Medication(id="MED-052", name="Midostaurin", category="Targeted",
                   dose=50, unit="mg", route="Oral", frequency="BID days 8-21",
                   start_date="2024-03-12", status="Active", cycle_number=1),
        Medication(id="MED-053", name="Posaconazole", category="Supportive",
                   dose=300, unit="mg", route="Oral", frequency="Daily",
                   start_date="2024-03-05", status="Active"),
        Medication(id="MED-054", name="Acyclovir", category="Supportive",
                   dose=400, unit="mg", route="Oral", frequency="BID",
                   start_date="2024-03-05", status="Active"),
    ],
    adverse_events=[
        AdverseEvent(id="AE-050", term="Febrile Neutropenia", category="Blood",
                     grade=4, onset="2024-03-12", outcome="Resolving",
                     action="Hospitalization", related_to_treatment=True, date="2024-03-12",
                     notes="ANC 0.1. Fever 39.2C. Broad-spectrum antibiotics started. Defervesced."),
        AdverseEvent(id="AE-051", term="Thrombocytopenia", category="Blood",
                     grade=4, onset="2024-03-10", outcome="Ongoing",
                     action="None", related_to_treatment=True, date="2024-03-10",
                     notes="Expected nadir. Platelets 8k. Platelet transfusions daily."),
        AdverseEvent(id="AE-052", term="Mucositis", category="Gastrointestinal",
                     grade=3, onset="2024-03-14", outcome="Resolving",
                     action="None", related_to_treatment=True, date="2024-03-14",
                     notes="WHO Grade 3. Morphine PCA for pain. Oral care protocol initiated."),
        AdverseEvent(id="AE-053", term="Nausea/Vomiting", category="Gastrointestinal",
                     grade=2, onset="2024-03-05", outcome="Resolving",
                     action="None", related_to_treatment=True, date="2024-03-05"),
    ],
    progression_assessments=[
        ProgressionAssessment(id="PA-050", date="2024-03-01", method="BM Biopsy",
                              response="NE", tumor_burden_mm=0, percent_change=0,
                              target_lesions=0, non_target_lesions="Blasts 42%",
                              new_lesions=False, notes="Diagnostic BM: 42% blasts, FLT3-ITD+ confirmed"),
    ],
    cycles=[
        TreatmentCycle(id="CYC-060", cycle_number=1, start_date="2024-03-05",
                       status="Active", notes="Induction — 7+3 regimen"),
    ],
    visits=[
        Visit(id="V-050", date="2024-03-01", type="Screening", provider="Dr. Larsson",
              notes="New AML diagnosis. FLT3-ITD confirmed. ECHO normal (EF 62%).", ecog=1,
              vitals=VitalSigns(bp="136/84", hr=88, temp=36.9, weight=88.0, o2sat=97)),
        Visit(id="V-051", date="2024-03-12", type="Unscheduled", provider="Dr. Larsson",
              notes="Febrile neutropenia. Admitted to BMT unit.", ecog=2,
              vitals=VitalSigns(bp="98/62", hr=118, temp=39.2, weight=86.0, o2sat=95)),
    ],
)

PATIENTS: dict[str, Patient] = {
    p.id: p for p in [PATIENT_1, PATIENT_2, PATIENT_3, PATIENT_4, PATIENT_5, PATIENT_6]
}

def get_all_patients() -> list[Patient]:
    return list(PATIENTS.values())

def get_patient(patient_id: str) -> Optional[Patient]:
    return PATIENTS.get(patient_id)
